#!/bin/sh
# from https://github.com/ngynLk/polybar-themes/blob/master/blocks/get_workspace
# depends on `jq'
i3-msg -t get_workspaces \
  | jq '.[] | select(.focused==true).name' \
  | cut -d"\"" -f2

